const express = require('express');
const cors = require('cors');
const app = express();
app.use(cors());
app.use(express.json());

let users = [];
let orders = [];
let services = [
{id:101,cat:"Instagram",name:"IG Followers MIXED 100K Refill",price:35,min:100,max:100000,status:"Active"},
{id:102,cat:"Instagram",name:"IG Followers REAL PH",price:95,min:100,max:10000,status:"Active"},
{id:103,cat:"Instagram",name:"IG Likes REAL No Drop",price:12,min:50,max:50000,status:"Active"},
{id:201,cat:"Facebook",name:"FB Page Followers REAL",price:55,min:100,max:100000,status:"Active"},
{id:301,cat:"TikTok",name:"TikTok Followers REAL REFILL",price:52,min:100,max:1000000,status:"Active"},
{id:401,cat:"YouTube",name:"YT Subs REAL REFILL",price:175,min:100,max:10000,status:"Active"}
];
const ADMIN = {email:"admin@boosthub.ph", pass:"admin123"};

app.get('/', (req,res)=>{
res.send(`<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>BoostHub</title>
<style>body{margin:0;background:#0a0a0f;color:#fff;font-family:Arial}.header{background:#12121a;padding:14px;border-bottom:1px solid #222;display:flex;justify-content:space-between;align-items:center}.logo{color:#a855f7;font-weight:900}.btn{background:#a855f7;color:#fff;border:none;padding:10px 16px;border-radius:8px;font-weight:bold}.tab{background:#1e1e2e;color:#888;padding:8px 14px;border-radius:20px;border:none;margin:3px}.tab.active{background:#a855f7;color:#fff}.search{width:100%;padding:12px;background:#1a1a27;border:1px solid #333;border-radius:10px;color:#fff;margin:10px 0;box-sizing:border-box}.card{background:#14141f;border:1px solid #232336;border-radius:12px;padding:14px;margin-bottom:10px}.price{color:#22c55e;font-weight:bold;float:right}.auth-screen{position:fixed;top:0;left:0;width:100%;height:100%;background:#07070a;display:flex;justify-content:center;align-items:center;z-index:100;padding:15px;box-sizing:border-box}.auth-box{background:#14141f;padding:25px;border-radius:16px;width:100%;max-width:380px;border:1px solid #2a2a3a}input,select{width:100%;padding:12px;background:#0f0f17;border:1px solid #333;border-radius:10px;color:#fff;margin:7px 0;box-sizing:border-box}.main{display:none}.main.show{display:block}</style></head><body>
<div class="auth-screen" id="authScreen"><div class="auth-box"><div style="text-align:center"><div style="font-size:28px;font-weight:900;color:#a855f7">BOOSTHUB.PH</div><small style="color:#888">Login to continue</small></div><h3 id="authTitle">Login</h3><input id="email" placeholder="Email"><input id="password" type="password" placeholder="Password"><button class="btn" style="width:100%" onclick="doAuth()">Submit</button><p style="text-align:center;color:#888;font-size:13px"><span onclick="switchAuth()" id="switchText" style="color:#a855f7;cursor:pointer">No account? Create account</span></p></div></div>
<div class="main" id="mainSite"><div class="header"><div class="logo">BOOSTHUB</div><div><span id="balance" style="color:#22c55e;font-weight:900;background:#1a2e1a;padding:6px 10px;border-radius:20px">P0</span> <button class="btn" style="background:#222;padding:6px 10px;font-size:12px" onclick="logout()">Logout</button></div></div><div style="max-width:1100px;margin:auto;padding:12px"><div id="userInfo" style="background:#12121a;padding:12px;border-radius:10px;margin-bottom:12px;border:1px solid #a855f7;font-size:13px"></div><input id="searchBox" class="search" placeholder="Search services..." onkeyup="showList()"><div id="tabs"></div><div id="list"></div><h3>My Orders: <span id="cnt">0</span></h3><div id="orders"></div></div></div>
<script>
var currentCat="All";var cats=["All","Instagram","Facebook","TikTok","YouTube"];var isLogin=true;var currentUser=null;var services=[];
async function loadServices(){var r=await fetch("/api/services");services=await r.json();buildTabs();showList();}
function checkLogin(){var u=localStorage.getItem("boost_user");if(u){currentUser=JSON.parse(u);document.getElementById("authScreen").style.display="none";document.getElementById("mainSite").classList.add("show");document.getElementById("balance").innerText="P"+currentUser.balance;document.getElementById("userInfo").innerHTML="Hi <b>"+currentUser.email+"</b> | Balance: <b style=color:#22c55e>P"+currentUser.balance+"</b>";loadServices();loadOrders();refreshBalance();}else{document.getElementById("authScreen").style.display="flex";}}
function switchAuth(){isLogin=!isLogin;document.getElementById("authTitle").innerText=isLogin?"Login":"Create Account";document.getElementById("switchText").innerText=isLogin?"No account? Create":"Have account? Login";}
async function doAuth(){var e=document.getElementById("email").value;var p=document.getElementById("password").value;if(!e||!p){alert("Fill all");return;}var url=isLogin?"/api/login":"/api/register";var r=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:e,pass:p})});var d=await r.json();if(d.error){alert(d.error);return;}currentUser=d.user;localStorage.setItem("boost_user",JSON.stringify(d.user));checkLogin();}
function logout(){localStorage.removeItem("boost_user");location.reload();}
function buildTabs(){var h="";for(var i=0;i<cats.length;i++){var c=cats[i];var active=c==currentCat?"active":"";h+='<button class="tab '+active+'" onclick="pickCat(\\''+c+'\\')">'+c+'</button>';}document.getElementById("tabs").innerHTML=h;}
function pickCat(c){currentCat=c;buildTabs();showList();}
function showList(){var q=document.getElementById("searchBox").value.toLowerCase();var html="";for(var i=0;i<services.length;i++){var s=services[i];if(s.status!="Active")continue;if(currentCat!="All"&&s.cat!=currentCat)continue;if(q&&s.name.toLowerCase().indexOf(q)==-1)continue;html+='<div class="card"><div><b>'+s.id+' - '+s.name+'</b><br><small style=color:#888>Min '+s.min+' Max '+s.max+' | '+s.cat+'</small></div><div style="margin-top:8px;display:flex;justify-content:space-between"><div class="price">P'+s.price+'/1k</div><button class="btn" onclick="doOrder('+s.id+')">Order</button></div></div>';}document.getElementById("list").innerHTML=html;}
async function doOrder(id){var s=services.find(x=>x.id==id);var link=prompt("Paste Link for "+s.name);if(!link)return;var qty=prompt("Quantity Min "+s.min);if(!qty)return;var total=(qty/1000)*s.price;if(currentUser.balance<total){alert("Kulang balance! Need P"+total.toFixed(2)+" pero P"+currentUser.balance+" lang");return;}var r=await fetch("/api/order",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({userId:currentUser.id,serviceId:id,serviceName:s.name,link:link,qty:qty,total:total})});var d=await r.json();if(d.error){alert(d.error);return;}alert("Order Success! ID "+d.order.id);refreshBalance();loadOrders();}
async function loadOrders(){if(!currentUser)return;var r=await fetch("/api/orders?userId="+currentUser.id);var d=await r.json();document.getElementById("cnt").innerText=d.length;var h="";for(var i=d.length-1;i>=0;i--){var o=d[i];h+='<div class="card"><b>#'+o.id+' '+o.serviceName+'</b><br><small>'+o.link+' | '+o.qty+' | P'+o.total.toFixed(2)+' | '+o.status+'</small></div>';}document.getElementById("orders").innerHTML=h;}
async function refreshBalance(){if(!currentUser)return;var r=await fetch("/api/user/"+currentUser.id);var d=await r.json();if(d.user){currentUser=d.user;localStorage.setItem("boost_user",JSON.stringify(d.user));document.getElementById("balance").innerText="P"+d.user.balance;}}
checkLogin();
</script></body></html>`);
});

app.get('/admin',(req,res)=>{
res.send(`<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Admin</title>
<style>body{background:#050507;color:#fff;font-family:Arial;padding:10px;margin:0}.header{background:#12121a;padding:15px;border-radius:10px;margin-bottom:15px;display:flex;justify-content:space-between;align-items:center}.stats{display:grid;grid-template-columns:1fr 1fr 1fr 1fr;gap:8px;margin-bottom:15px}.stat{background:#14141f;border:1px solid #232336;padding:12px;border-radius:10px;text-align:center}.stat b{font-size:18px;color:#a855f7;display:block}.card{background:#14141f;border:1px solid #232336;padding:12px;border-radius:10px;margin-bottom:8px}.btn{background:#a855f7;color:#fff;border:none;padding:7px 12px;border-radius:6px;margin:2px;font-size:12px}.btn-green{background:#22c55e;color:#000;font-weight:bold}.btn-red{background:#ef4444}.btn-gray{background:#2a2a3a}input,select{padding:8px;background:#0f0f17;border:1px solid #333;border-radius:6px;color:#fff;margin:3px}.search{width:100%;padding:10px;background:#1a1a27;border:1px solid #333;border-radius:8px;color:#fff;margin-bottom:10px;box-sizing:border-box}.tabs{display:flex;gap:6px;margin-bottom:12px;flex-wrap:wrap}.tab{padding:8px 14px;border-radius:20px;border:none;background:#1e1e2e;color:#888}.tab.active{background:#a855f7;color:#fff}.section{display:none}.section.active{display:block}.row{display:flex;gap:6px;flex-wrap:wrap;align-items:center}</style></head><body>
<div id="loginBox" style="max-width:400px;margin:60px auto;text-align:center"><h2>Admin Login</h2><input id="adminEmail" placeholder="Email" style="width:100%;box-sizing:border-box" value="admin@boosthub.ph"><br><input id="adminPass" type="password" placeholder="Password" style="width:100%;box-sizing:border-box" value="admin123"><br><br><button class="btn" style="width:100%;padding:10px" onclick="login()">Login to Admin</button><br><br><small style="color:#666">admin@boosthub.ph / admin123</small></div>
<div id="adminBox" style="display:none"><div class="header"><div><b style="color:#a855f7;font-size:18px">BOOSTHUB ADMIN</b><br><small style="color:#666">Full Control</small></div><div><button class="btn btn-gray" onclick="location.href='/'">View Site</button> <button class="btn btn-red" onclick="logout()">Logout</button></div></div><div class="stats"><div class="stat"><b id="totalUsers">0</b><small>Users</small></div><div class="stat"><b id="totalOrders">0</b><small>Orders</small></div><div class="stat"><b id="totalRev">P0</b><small>Sales</small></div><div class="stat"><b id="totalServices">0</b><small>Services</small></div></div><div class="tabs"><button class="tab active" onclick="showTab('users')">Users & Points</button><button class="tab" onclick="showTab('orders')">Orders</button><button class="tab" onclick="showTab('services')">Services</button></div>
<div id="usersSec" class="section active"><input id="userSearch" class="search" placeholder="Search email..." onkeyup="filterUsers()"><div id="usersList"></div></div>
<div id="ordersSec" class="section"><input id="orderSearch" class="search" placeholder="Search order..." onkeyup="filterOrders()"><div id="ordersList"></div></div>
<div id="servicesSec" class="section"><div class="card" style="border:1px solid #a855f7"><b>Add New Service</b><br><div class="row"><select id="newCat"><option>Instagram</option><option>Facebook</option><option>TikTok</option><option>YouTube</option></select><input id="newName" placeholder="Service Name" style="width:200px"><input id="newPrice" type="number" placeholder="Price" style="width:70px"><input id="newMin" type="number" placeholder="Min" style="width:60px"><input id="newMax" type="number" placeholder="Max" style="width:70px"><button class="btn btn-green" onclick="addService()">+ Add</button></div></div><div id="servicesList"></div></div></div>
<script>
var token="";var allUsers=[];var allOrders=[];var allServices=[];
function showTab(t){document.querySelectorAll('.tab').forEach(b=>b.classList.remove('active'));document.querySelectorAll('.section').forEach(s=>s.classList.remove('active'));if(t=='users'){document.querySelectorAll('.tab')[0].classList.add('active');document.getElementById('usersSec').classList.add('active');}else if(t=='orders'){document.querySelectorAll('.tab')[1].classList.add('active');document.getElementById('ordersSec').classList.add('active');}else{document.querySelectorAll('.tab')[2].classList.add('active');document.getElementById('servicesSec').classList.add('active');}}
function logout(){localStorage.removeItem("admin_token");location.reload();}
async function login(){var email=document.getElementById("adminEmail").value;var pass=document.getElementById("adminPass").value;var r=await fetch("/api/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:email,pass:pass})});var d=await r.json();if(!d.ok){alert("Wrong admin credentials");return;}token=email+"|"+pass;localStorage.setItem("admin_token",token);document.getElementById("loginBox").style.display="none";document.getElementById("adminBox").style.display="block";loadAll();}
async function loadAll(){var ru=await fetch("/api/all-users?token="+encodeURIComponent(token));allUsers=await ru.json();var ro=await fetch("/api/all-orders?token="+encodeURIComponent(token));allOrders=await ro.json();var rs=await fetch("/api/services");allServices=await rs.json();document.getElementById("totalUsers").innerText=allUsers.length;document.getElementById("totalOrders").innerText=allOrders.length;var rev=0;allOrders.forEach(o=>rev+=o.total||0);document.getElementById("totalRev").innerText="P"+rev.toFixed(0);document.getElementById("totalServices").innerText=allServices.length;renderUsers(allUsers);renderOrders(allOrders);renderServices(allServices);}
function renderUsers(list){var h="";for(var i=0;i<list.length;i++){var u=list[i];h+='<div class="card"><div style="display:flex;justify-content:space-between;flex-wrap:wrap"><div><b style="color:#a855f7">'+u.email+'</b><br><small>ID:'+u.id.slice(-6)+' | Balance:</small> <b style="color:#22c55e">P'+u.balance+'</b><br><small>Orders: '+(allOrders.filter(o=>o.userId==u.id).length)+'</small></div><div><div class="row"><input id="pts_'+u.id+'" type="number" placeholder="100" style="width:70px"><button class="btn btn-green" onclick="addPts(\\''+u.id+'\\')">+Add</button><button class="btn" onclick="setPts(\\''+u.id+'\\')">Set</button><button class="btn btn-red" onclick="delUser(\\''+u.id+'\\')">Del</button></div></div></div></div>';}document.getElementById("usersList").innerHTML=h||"No users";}
function renderOrders(list){var h="";for(var i=list.length-1;i>=0;i--){var o=list[i];h+='<div class="card"><div style="display:flex;justify-content:space-between;flex-wrap:wrap"><div><b>#'+o.id+' '+o.serviceName+'</b><br><small style="color:#a855f7">'+o.userEmail+'</small><br><small>Qty:'+o.qty+' | P'+o.total.toFixed(2)+' | <b>'+o.status+'</b></small></div><div><button class="btn btn-green" onclick="updOrder('+o.id+',\\'Completed\\')">Complete</button><button class="btn btn-red" onclick="delOrder('+o.id+')">Del</button></div></div></div>';}document.getElementById("ordersList").innerHTML=h||"No orders";}
function renderServices(list){var h="";for(var i=0;i<list.length;i++){var s=list[i];h+='<div class="card"><div style="display:flex;justify-content:space-between;flex-wrap:wrap"><div><b>'+s.id+' - '+s.name+'</b> <small>['+s.status+']</small><br><small>'+s.cat+' | P'+s.price+'/1k | Min:'+s.min+' Max:'+s.max+'</small></div><div><div class="row"><input id="price_'+s.id+'" type="number" value="'+s.price+'" style="width:60px"><button class="btn" onclick="updPrice('+s.id+')">Save</button><button class="btn btn-red" onclick="delService('+s.id+')">Del</button></div></div></div></div>';}document.getElementById("servicesList").innerHTML=h;}
function filterUsers(){var q=document.getElementById("userSearch").value.toLowerCase();renderUsers(allUsers.filter(u=>u.email.toLowerCase().includes(q)));}function filterOrders(){var q=document.getElementById("orderSearch").value.toLowerCase();renderOrders(allOrders.filter(o=>o.userEmail.toLowerCase().includes(q)||o.serviceName.toLowerCase().includes(q)));}
async function addPts(uid){var pts=document.getElementById("pts_"+uid).value;if(!pts)return;await fetch("/api/add-points",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({userId:uid,points:parseInt(pts),token:token})});loadAll();}
async function setPts(uid){var pts=document.getElementById("pts_"+uid).value;if(!pts)return;await fetch("/api/set-points",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({userId:uid,points:parseInt(pts),token:token})});loadAll();}
async function delUser(uid){if(!confirm("Delete user?"))return;await fetch("/api/admin/delete-user",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({userId:uid,token:token})});loadAll();}
async function updOrder(id,st){await fetch("/api/admin/update-order",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:id,status:st,token:token})});loadAll();}
async function delOrder(id){if(!confirm("Delete order?"))return;await fetch("/api/admin/delete-order",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:id,token:token})});loadAll();}
async function addService(){var cat=document.getElementById("newCat").value;var name=document.getElementById("newName").value;var price=document.getElementById("newPrice").value;var min=document.getElementById("newMin").value;var max=document.getElementById("newMax").value;if(!name||!price)return alert("Fill name & price");await fetch("/api/admin/add-service",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({cat:cat,name:name,price:parseFloat(price),min:parseInt(min)||100,max:parseInt(max)||10000,token:token})});document.getElementById("newName").value="";loadAll();}
async function updPrice(id){var price=document.getElementById("price_"+id).value;await fetch("/api/admin/update-service",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:id,price:parseFloat(price),token:token})});loadAll();}
async function delService(id){if(!confirm("Delete service?"))return;await fetch("/api/admin/delete-service",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:id,token:token})});loadAll();}
var saved=localStorage.getItem("admin_token");if(saved){token=saved;document.getElementById("loginBox").style.display="none";document.getElementById("adminBox").style.display="block";loadAll();}
</script></body></html>`);
});

function checkAdmin(token){if(!token) return false;var parts=token.split("|");return parts[0]===ADMIN.email && parts[1]===ADMIN.pass;}
app.get('/api/services',(req,res)=>{res.json(services);});
app.get('/api/user/:id',(req,res)=>{var u=users.find(x=>x.id==req.params.id);res.json({user:u});});
app.get('/api/orders',(req,res)=>{res.json(orders.filter(o=>o.userId==req.query.userId));});
app.get('/api/all-users',(req,res)=>{if(!checkAdmin(req.query.token)) return res.json([]);res.json(users);});
app.get('/api/all-orders',(req,res)=>{if(!checkAdmin(req.query.token)) return res.json([]);res.json(orders);});
app.post('/api/admin/login',(req,res)=>{if(req.body.email===ADMIN.email && req.body.pass===ADMIN.pass) res.json({ok:true}); else res.json({ok:false});});
app.post('/api/register',(req,res)=>{if(users.find(u=>u.email==req.body.email)) return res.json({error:"Email exists"});var u={id:Date.now().toString(),email:req.body.email,pass:req.body.pass,balance:0};users.push(u);res.json({user:{id:u.id,email:u.email,balance:u.balance}});});
app.post('/api/login',(req,res)=>{var u=users.find(x=>x.email==req.body.email&&x.pass==req.body.pass);if(!u) return res.json({error:"Wrong email/pass"});res.json({user:{id:u.id,email:u.email,balance:u.balance}});});
app.post('/api/order',(req,res)=>{var u=users.find(x=>x.id==req.body.userId);if(!u) return res.json({error:"User not found"});if(u.balance<req.body.total) return res.json({error:"Kulang balance"});u.balance-=req.body.total;var o={id:Math.floor(10000+Math.random()*90000),userId:u.id,userEmail:u.email,serviceId:req.body.serviceId,serviceName:req.body.serviceName,link:req.body.link,qty:req.body.qty,total:req.body.total,status:"Pending"};orders.push(o);res.json({order:o});});
app.post('/api/add-points',(req,res)=>
